### ISSUE TITLE
Wyciąganie danych z tooltipa

### ISSUE THREAD

**Issue by WolnyMikolaj** [ergis-accounting-app/ergis-accounting-app#36]
Księgowi chcieliby mieć możliwość wyciągnięcia masowo wszystkich danych, które dostarcza tooltip. Nie wiem jeszcze do końca jak to zbudować ale jakbym musiał odpowiedzieć na szybko to zasugerowałbym tabele pojawiającą się po prawej stronie od wyników końcowych. Tabela powinna się pojawiać i chować na wciśnięcie guzika. Myślę, że tooltip i tak może zostać dla szybkiego podglądu natomiast rozwijalna tabele po prawej da im większą kontrolę nad wynikami

**Comment by joker876** [comment]
+ do poprawy że tooltip znika jak się zjedzie myszką z tabeli (jak się najedzie na inny rząd nie ma znikać)
