### ISSUE TITLE
Problemy z kopiowaniem do Excela MPK: 0000 jako 0 i kopiowaniu "i" tooltipa jako "info"

### ISSUE THREAD

**Issue by WolnyMikolaj** [ergis-accounting-app/ergis-accounting-app#59]
- Jeśli mpk jest 0000 to przy kopiowaniu do excela zmienia się na 0
- Przy kopiowaniu wyników do excela kopiuje się również dodatkowa kolumna info

![Image](https://github.com/ergis-accounting-app/ergis-accounting-app/assets/136742392/a1d3a554-4560-480a-98d3-e870f565a333)

**Comment by joker876** [comment]
Niestety niewiele można z tym zrobić. MPK kopiuje się dobrze, ale excel interpretuje to jako liczba i skraca po prostu do jednego zera. W przypadku info można zrobić żeby się nie kopiowało, ale i tak będzie się kopiować pusta komórka (co jak dobrze widzę nie jest wielkim problemem, ale wciąż).

Jedyne co można z tym zrobić to przycisk do manualnego skopiowania całej tabeli.
